import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os
import sys

# Add root to sys path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils.helpers import get_project_root, load_data, save_data

def preprocess_and_engineer(df):
    """
    Applies preprocessing, normalization, and feature engineering to the raw dataset.
    """
    # 1. Convert Dates
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df.set_index('Date', inplace=True)
    else:
        df.index = pd.to_datetime(df.index)
        
    # 2. Handle missing values
    # ffill and bfill are deprecated in recent pandas, so we use ffill() and bfill() methods directly
    df.ffill(inplace=True)
    df.bfill(inplace=True)
    
    # Check if 'Close' column exists
    if 'Close' not in df.columns:
        raise ValueError("The 'Close' column is missing from the data. Please check the raw data.")
    
    # 3. Feature Engineering
    # Moving Averages
    df['MA_7'] = df['Close'].rolling(window=7).mean()
    df['MA_30'] = df['Close'].rolling(window=30).mean()
    
    # Daily Returns
    df['Daily_Return'] = df['Close'].pct_change()
    
    # Rolling Volatility (30 days)
    df['Rolling_Volatility_30'] = df['Daily_Return'].rolling(window=30).std()
    
    # Lag Features (T-1, T-2, T-3)
    df['Lag_1'] = df['Close'].shift(1)
    df['Lag_2'] = df['Close'].shift(2)
    df['Lag_3'] = df['Close'].shift(3)
    
    # Drop NaNs generated by rolling and shifting
    df.dropna(inplace=True)
    
    # 4. Normalization
    # We will keep the unnormalized columns and add normalized ones.
    scaler = MinMaxScaler()
    
    # Normalize the numerical columns
    cols_to_scale = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'MA_7', 'MA_30', 'Lag_1', 'Lag_2', 'Lag_3']
    # Filter only columns that actually exist
    cols_to_scale = [c for c in cols_to_scale if c in df.columns]
    
    if len(cols_to_scale) > 0:
        scaled_data = scaler.fit_transform(df[cols_to_scale])
        
        # Create normalized columns with prefix 'Norm_'
        for i, col in enumerate(cols_to_scale):
            df[f'Norm_{col}'] = scaled_data[:, i]
            
    return df

if __name__ == "__main__":
    root = get_project_root()
    raw_path = os.path.join(root, "data", "raw_data.csv")
    processed_path = os.path.join(root, "data", "processed_data.csv")
    
    print("Loading raw data...")
    try:
        raw_df = load_data(raw_path)
    except FileNotFoundError:
        print(f"File not found at {raw_path}. Please run src/data_pipeline.py first.")
        sys.exit(1)
        
    print("Applying preprocessing and feature engineering...")
    processed_df = preprocess_and_engineer(raw_df)
    
    save_data(processed_df, processed_path)
    print("Feature engineering complete. Data ready for modeling.")
